dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.45
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.45
- name: my-spring-boot-app-20180306
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
